In [29]:
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
## Creating object of CountVectorizer, PorterStemmer
ps=PorterStemmer()
lemma = WordNetLemmatizer()
vectorizer = CountVectorizer(max_features=150)

In [2]:
corpus = [
    "Artificial intelligence is transforming the world.",
    "Natural language processing enables machines to understand text.",
    "Machine learning models require large datasets for training.",
    "Deep learning uses neural networks to solve complex problems.",
    "Computer vision allows computers to interpret visual information.",
    "Robotics combines engineering and computer science fields.",
    "Data science involves extracting insights from structured data.",
    "Algorithms are the core of modern computing systems.",
    "Big data technologies handle massive amounts of information.",
    "Cloud computing provides scalable resources for applications."
]

## Using PorterStemmer

In [20]:
ps_corpus=[]
stop_words = set(stopwords.words("english"))

for sent in corpus:
    sentence = sent.lower().replace(".", "")
    sentence = sentence.split()
    sentence = [ps.stem(word) for word in sentence if word not in stop_words]
    sentence = " ".join(sentence)

    ps_corpus.append(sentence)

print(ps_corpus)

['artifici intellig transform world', 'natur languag process enabl machin understand text', 'machin learn model requir larg dataset train', 'deep learn use neural network solv complex problem', 'comput vision allow comput interpret visual inform', 'robot combin engin comput scienc field', 'data scienc involv extract insight structur data', 'algorithm core modern comput system', 'big data technolog handl massiv amount inform', 'cloud comput provid scalabl resourc applic']

In [39]:
## Creating Vector
ps_vec = vectorizer.fit_transform(ps_corpus).toarray()

for idx in range(5): print(f"Sentence: {ps_corpus[idx]}\nArray: {ps_vec[idx]}"); print('-'*50)

## creating a Dataframe
words=set()
for sentence in ps_corpus:
    for word in sentence.split():
        words.add(word)

vocab=list(words)

ps_df = pd.DataFrame(ps_vec, columns=vocab)
print(f"\nShape of the Dataframe: {ps_df.shape}\n")
ps_df

Sentence: artifici intellig transform world
Array: [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
--------------------------------------------------
Sentence: natur languag process enabl machin understand text
Array: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]
--------------------------------------------------
Sentence: machin learn model requir larg dataset train
Array: [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
--------------------------------------------------
Sentence: deep learn use neural network solv complex problem
Array: [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0]
--------------------------------------------------
Sentence: comput vision allow comput interpret visual inform
Array: [0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0]
--------------------------------------------------

Shape of the Dataframe: (10, 54)

,modern,involv,transform,enabl,extract,algorithm,deep,complex,provid,big,...,amount,artifici,model,technolog,data,allow,insight,process,larg,comput
0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
4,0,1,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,1,1,0
5,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
8,0,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9,0,0,0,1,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0

## Using WordNetLemmatizer

In [32]:
lemma_corpus=[]

for sent in corpus:
    sentence = sent.lower().replace(".", "")
    sentence = sentence.split()
    sentence = [lemma.lemmatize(word) for word in sentence if word not in stop_words]
    sentence = " ".join(sentence)

    lemma_corpus.append(sentence)

print(lemma_corpus)

['artificial intelligence transforming world', 'natural language processing enables machine understand text', 'machine learning model require large datasets training', 'deep learning us neural network solve complex problem', 'computer vision allows computer interpret visual information', 'robotics combine engineering computer science field', 'data science involves extracting insight structured data', 'algorithm core modern computing system', 'big data technology handle massive amount information', 'cloud computing provides scalable resource application']

In [38]:
## Creating Vector
lemma_vec = vectorizer.fit_transform(lemma_corpus).toarray()

for idx in range(5): print(f"Sentence: {lemma_corpus[idx]}\nArray: {lemma_vec[idx]}\n"); print('-'*50)

## creating a Dataframe
words=set()
for sentence in lemma_corpus:
    for word in sentence.split():
        words.add(word)

vocab=list(words)

lemma_df = pd.DataFrame(lemma_vec, columns=vocab)
print(f"\nShape of the Dataframe: {lemma_df.shape}\n")
lemma_df

Sentence: artificial intelligence transforming world
Array: [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]

--------------------------------------------------
Sentence: natural language processing enables machine understand text
Array: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]

--------------------------------------------------
Sentence: machine learning model require large datasets training
Array: [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]

--------------------------------------------------
Sentence: deep learning us neural network solve complex problem
Array: [0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0
 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0]

--------------------------------------------------
Sentence: computer vision allows computer interpret visual information
Array: [0 1 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0]

--------------------------------------------------

Shape of the Dataframe: (10, 55)

,modern,datasets,engineering,computing,intelligence,processing,algorithm,involves,deep,training,...,robotics,information,amount,model,data,us,insight,application,artificial,language
0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
4,0,1,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,1,1,0
5,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
8,0,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
9,0,0,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0